### ISSUE TITLE
doesn't seem to be published to @types/globby

### ISSUE THREAD

**Issue by matthewmueller** [typings/typed-globby#2]
```
error Couldn't find package "@types/globby" on the "npm" registry.
error Couldn't find package "@types/npm-globby" on the "npm" registry.
```

**Comment by matthewmueller** [comment]
doh, realized @types comes from DefinitelyTyped!

**Comment by blakeembrey** [comment]
Unfortunately, yeah - we've been waiting https://github.com/Microsoft/types-publisher/issues/4. Our hack for now has been to NPM's github installation feature so you can do `npm install types/npm-globby` (and we're renaming repos slowly also).
